# Generated by Django 5.2.8 on 2025-11-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehf_invoice', '0005_supplier_alternate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, upload_to='invoice_attachments/%Y/'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='beskrivelse'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='name',
            field=models.TextField(verbose_name='navn'),
        ),
    ]
